In [1]:
import torch
import numpy as np

In [2]:
# Create tensor
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [6]:
# Create tensor from np.array
np_array = np.array(data)
x_np = torch.tensor(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [11]:
# Create tensor from another tensor
x_one = torch.ones_like(x_data)
print(x_one)
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[1, 1],
        [1, 1]])


tensor([[0.7669, 0.8848],
        [0.9832, 0.5702]])

In [15]:
# With random or constant values:

shape = (2, 3,)
shape

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5782, 0.8737, 0.4343],
        [0.9874, 0.0680, 0.2010]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [20]:
# Attribute

rand_tensor.dtype
rand_tensor.shape
rand_tensor.device

device(type='cpu')

In [21]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [41]:
# Index and slicing

tensor = torch.ones(4, 4)
tensor[:, 1] = 0
tensor[..., -1] = 2
print(tensor)

tensor([[1., 0., 1., 2.],
        [1., 0., 1., 2.],
        [1., 0., 1., 2.],
        [1., 0., 1., 2.]])


In [51]:
# Join tensor

t1 = torch.cat([tensor, tensor, tensor], dim=-2)
print(t1)

tensor([[1., 0., 1., 2.],
        [1., 0., 1., 2.],
        [1., 0., 1., 2.],
        [1., 0., 1., 2.],
        [1., 0., 1., 2.],
        [1., 0., 1., 2.],
        [1., 0., 1., 2.],
        [1., 0., 1., 2.],
        [1., 0., 1., 2.],
        [1., 0., 1., 2.],
        [1., 0., 1., 2.],
        [1., 0., 1., 2.]])


In [58]:
# Arithmetic operations

# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 4.],
        [1., 0., 1., 4.],
        [1., 0., 1., 4.],
        [1., 0., 1., 4.]])

In [59]:
# Single-element tensor

agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

16.0 <class 'float'>


In [60]:
# In-place operations (has suffix _ )

tensor.add_(5)
tensor


tensor([[6., 5., 6., 7.],
        [6., 5., 6., 7.],
        [6., 5., 6., 7.],
        [6., 5., 6., 7.]])

In [63]:
# Tensor to np.array
n = tensor.numpy()

tensor.add_(1)
print(f"t: {tensor}")
print(f"n: {n}")


t: tensor([[7., 6., 7., 8.],
        [7., 6., 7., 8.],
        [7., 6., 7., 8.],
        [7., 6., 7., 8.]])
n: [[7. 6. 7. 8.]
 [7. 6. 7. 8.]
 [7. 6. 7. 8.]
 [7. 6. 7. 8.]]
