In [19]:
import numpy as np

print(np.__version__)

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))
print(a.ndim)

arr3 = np.array(1, ndmin=5)
print(arr3)

1.20.1
[1 2 3 4 5]
<class 'numpy.ndarray'>
1
[[[[[1]]]]]


In [35]:
arr2 = np.array([[1, 2, 3, 5, 4], [4, 5, 6, 1, 2], [7, 8, 9, 9, 7]])
print(arr2)
print(arr2[1, -1])
# slicing
print(arr2[-1, 1:])
print(arr2[0, -3:-1])

[[1 2 3 5 4]
 [4 5 6 1 2]
 [7 8 9 9 7]]
2
[8 9 9 7]
[3 5]
[5 2]


In [41]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
# step
print(arr[1:5:2])
print(arr[::2])

[2 4]
[1 3 5 7]


In [51]:
str_arr = np.array(['hello', 'world'])
print(str_arr.dtype)
print(arr.dtype)
print(str_arr)

arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

# Converting Data Type on Existing Arrays
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

<U5
int32
['hello' 'world']
[b'1' b'2' b'3' b'4']
|S1
[1 2 3 4]
int32
[1 2 3]
int64


In [54]:
# The Difference Between Copy and View
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]


In [55]:
# Check if Array Owns it's Data
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [57]:
# Get the Shape of an Array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

(2, 4)
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [67]:
# Reshaping arrays
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)
print(newarr)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)

# Unknown Dimension
newarr = arr.reshape(2, 2, -1)
print(newarr)

# Flattening the arrays
newarr = arr.reshape(-1)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 2 3 4 5 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6 7 8]
